name: Terraform Production

on:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]

env:
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_env: prod

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-production
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/Role_OIDC_aws-infra-eks
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init -backend-config="key=envs/prod/terraform.tfstate"

      - name: Terraform Validate
        working-directory: infra
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -var-file=envs/prod/prod.tfvars

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -var-file=envs/prod/prod.tfvars
